import React from 'react';
import { Project, AIAnalysisResult } from '../types';

interface TableExportProps {
    id: string;
    projectName: string;
    date: string;
    location: string;
    radius: string;
    type: string;
    projects: Project[];
}

export const HiddenTableTemplate: React.FC<TableExportProps> = ({ 
    id, projectName, date, location, radius, type, projects 
}) => {
    return (
        <div id={id} className="fixed top-[-9999px] left-[-9999px] bg-white p-10 w-[1000px] z-[-1]">
            <div className="border-b-2 border-scbx pb-6 mb-6 flex justify-between items-end">
                <div>
                    <div className="text-sm font-bold text-scbx uppercase tracking-wider mb-1">COMPETITOR ANALYSIS REPORT</div>
                    <h1 className="text-3xl font-bold text-gray-900 leading-none">{projectName}</h1>
                </div>
                <div className="text-right">
                    <div className="text-sm text-gray-500">Generated by RERD</div>
                    <div className="text-xs text-gray-400">Date: {date}</div>
                </div>
            </div>
            
            <div className="grid grid-cols-3 gap-6 mb-8">
                <div className="bg-gray-50 p-4 rounded-lg border border-gray-100">
                    <div className="text-xs text-gray-400 uppercase font-bold tracking-wider mb-1">Search Location</div>
                    <div className="text-lg font-mono font-medium text-gray-700">{location}</div>
                </div>
                <div className="bg-gray-50 p-4 rounded-lg border border-gray-100">
                    <div className="text-xs text-gray-400 uppercase font-bold tracking-wider mb-1">Radius</div>
                    <div className="text-lg font-medium text-gray-700">{radius}</div>
                </div>
                <div className="bg-gray-50 p-4 rounded-lg border border-gray-100">
                    <div className="text-xs text-gray-400 uppercase font-bold tracking-wider mb-1">Property Type</div>
                    <div className="text-lg font-medium text-gray-700">{type}</div>
                </div>
            </div>

            <div className="mb-4">
                <h3 className="font-bold text-gray-800 text-lg mb-4">Competitors List</h3>
                <table className="w-full text-sm">
                    <thead>
                        <tr className="bg-gray-100 text-gray-600 border-b-2 border-gray-200">
                            <th className="px-4 py-3 text-left font-bold w-12">#</th>
                            <th className="px-4 py-3 text-left font-bold">Project Name</th>
                            <th className="px-4 py-3 text-left font-bold">Developer</th>
                            <th className="px-4 py-3 text-left font-bold">Type</th>
                            <th className="px-4 py-3 text-right font-bold">Price</th>
                            <th className="px-4 py-3 text-right font-bold">Dist. (km)</th>
                            <th className="px-4 py-3 text-right font-bold">Sold %</th>
                            <th className="px-4 py-3 text-right font-bold">Speed</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-200">
                        {projects.map((p, idx) => (
                            <tr key={p.projectId} className={idx % 2 === 0 ? "bg-white" : "bg-gray-50"}>
                                <td className="px-4 py-3 text-left font-mono text-gray-500">{idx + 1}</td>
                                <td className="px-4 py-3 text-left font-medium text-gray-800">{p.name}</td>
                                <td className="px-4 py-3 text-left text-gray-600">{p.developer}</td>
                                <td className="px-4 py-3 text-left text-gray-600 text-xs">{[...new Set(p.subUnits.map(u => u.type))].join(', ')}</td>
                                <td className="px-4 py-3 text-right font-mono text-gray-700 font-medium">{p.priceRange}</td>
                                <td className="px-4 py-3 text-right font-mono text-gray-600">{p.distance?.toFixed(2)}</td>
                                <td className="px-4 py-3 text-right text-green-600 font-bold">{p.percentSold}%</td>
                                <td className="px-4 py-3 text-right text-gray-600">{p.saleSpeed}</td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
            
            <div className="mt-8 text-center text-xs text-gray-400 border-t border-gray-100 pt-4">
                CONFIDENTIAL - Internal Use Only
            </div>
        </div>
    );
};

export const HiddenAIReportTemplate: React.FC<{
    id: string;
    analysis: AIAnalysisResult;
    stats: { total: number; avgPrice: string; avgSold: string; avgSpeed: string };
    date: string;
}> = ({ id, analysis, stats, date }) => {
    return (
        <div id={id} className="fixed top-[-9999px] left-[-9999px] bg-white p-8 w-[800px] h-auto min-h-[1131px] flex flex-col font-sans z-[-1]">
             <div className="flex justify-between items-start border-b-2 border-gray-800 pb-4 mb-6">
                <div>
                    <div className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-1">AI STRATEGIC ANALYSIS</div>
                    <h1 className="text-3xl font-bold text-gray-900 leading-none">Market Report</h1>
                </div>
                <div className="text-right">
                    <div className="text-sm font-semibold text-scbx">RERD Intelligence</div>
                    <div className="text-xs text-gray-400 mt-1">Date: {date}</div>
                </div>
            </div>

            <div className="grid grid-cols-12 gap-6 mb-6">
                <div className="col-span-7">
                    <div className="w-full aspect-[4/3] bg-gray-100 rounded-lg overflow-hidden border border-gray-200 relative shadow-sm">
                        <div id="tempAIExportMap" style={{ width: '100%', height: '100%' }}></div>
                    </div>
                </div>
                <div className="col-span-5 flex flex-col justify-between">
                    <div className="bg-gray-50 p-4 rounded-lg border border-gray-100 h-full flex flex-col justify-center gap-4">
                        <div className="text-center">
                            <div className="text-xs text-gray-400 font-bold uppercase tracking-wider">Total Competitors</div>
                            <div className="text-3xl font-bold text-gray-800 mt-1">{stats.total}</div>
                        </div>
                        <div className="h-px bg-gray-200 w-full"></div>
                        <div className="text-center">
                            <div className="text-xs text-gray-400 font-bold uppercase tracking-wider">Avg. Market Price</div>
                            <div className="text-3xl font-bold text-gray-800 mt-1">{stats.avgPrice}</div>
                        </div>
                        <div className="h-px bg-gray-200 w-full"></div>
                         <div className="grid grid-cols-2 gap-2">
                            <div className="text-center">
                                <div className="text-[10px] text-gray-400 font-bold uppercase">Avg Sold</div>
                                <div className="text-lg font-bold text-gray-700">{stats.avgSold}</div>
                            </div>
                            <div className="text-center">
                                <div className="text-[10px] text-gray-400 font-bold uppercase">Avg Speed</div>
                                <div className="text-lg font-bold text-gray-700">{stats.avgSpeed}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div className="flex-1 flex flex-col gap-5">
                 <div className="grid grid-cols-2 gap-5">
                    <div className="border border-gray-200 rounded-xl p-5 shadow-sm bg-white">
                        <h3 className="text-scbx font-bold text-lg mb-3">Market Overview</h3>
                        <div className="prose prose-sm text-gray-600 text-sm leading-relaxed" dangerouslySetInnerHTML={{ __html: analysis.market_overview }}></div>
                    </div>
                     <div className="border border-gray-200 rounded-xl p-5 shadow-sm bg-white">
                        <h3 className="text-blue-600 font-bold text-lg mb-3">Competitor Performance</h3>
                        <div className="prose prose-sm text-gray-600 text-sm leading-relaxed" dangerouslySetInnerHTML={{ __html: analysis.competitor_performance }}></div>
                    </div>
                 </div>
                 <div className="border border-gray-200 rounded-xl p-5 shadow-sm bg-blue-50/50 border-blue-100 flex-1">
                    <h3 className="text-purple-600 font-bold text-lg mb-3">Strategic Analysis & Recommendations</h3>
                    <div className="prose prose-sm text-gray-700 text-sm leading-relaxed" dangerouslySetInnerHTML={{ __html: analysis.competitive_analysis }}></div>
                </div>
            </div>
            
             <div className="mt-8 text-center text-[10px] text-gray-400 border-t border-gray-100 pt-2">
                Generated by RERD AI Module • Confidential • Data as of {date}
            </div>
        </div>
    );
};